# Generated by Django 5.1.4 on 2025-01-27 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='consultaion_fees',
        ),
        migrations.AddField(
            model_name='appointment',
            name='appointment_fees',
            field=models.DecimalField(decimal_places=2, default='100', max_digits=6),
        ),
        migrations.AddField(
            model_name='appointment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
