# Generated by Django 5.1.4 on 2025-01-28 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_remove_appointment_consultaion_fees_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='is_expired',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
