# Generated by Django 5.1.4 on 2025-01-20 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_billing_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
