# Generated by Django 5.1.4 on 2025-01-28 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_schedule_is_expired'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='is_expired',
            field=models.BooleanField(default=False),
        ),
    ]
