# Generated by Django 5.1.4 on 2025-01-28 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0004_alter_schedule_is_expired'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='is_expired',
        ),
    ]
