# Generated by Django 5.1.4 on 2025-01-21 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0005_customuser_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='consult_fees',
            field=models.DecimalField(blank=True, decimal_places=2, default=100, max_digits=6, null=True),
        ),
    ]
