# Generated by Django 5.1.4 on 2025-01-28 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0005_remove_schedule_is_expired'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='department',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='reason',
        ),
    ]
