# Generated by Django 5.1.4 on 2025-01-22 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0006_doctor_consult_fees'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='dep_image',
            field=models.ImageField(blank=True, null=True, upload_to='department/'),
        ),
    ]
