# Generated by Django 5.1.4 on 2025-02-07 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0010_patient_blood_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='blood_group',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3),
        ),
    ]
