# Generated by Django 5.1.4 on 2025-01-24 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0011_alter_patient_pat_mrd_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('Administrator', 'Administrator'), ('Doctor', 'Doctor'), ('Staff', 'Staff')], default='Patient', max_length=20),
        ),
    ]
