# Generated by Django 5.1.4 on 2025-02-07 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0012_medicalrecord_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalrecord',
            name='record_type',
        ),
    ]
