# Generated by Django 5.1.4 on 2025-01-24 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0013_alter_customuser_user_type_alter_doctor_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_number',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='employ_code',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='pat_mrd_no',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='employee_code',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
