# Generated by Django 5.1.4 on 2025-02-08 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0013_remove_medicalrecord_record_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='slug',
            field=models.SlugField(default='', max_length=32),
        ),
    ]
