# Generated by Django 5.1.4 on 2025-01-24 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0014_alter_appointment_appointment_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='license_number',
            field=models.CharField(blank=True, max_length=32, unique=True),
        ),
    ]
