# Generated by Django 5.1.4 on 2025-01-24 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0015_alter_doctor_license_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='license_number',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
    ]
