# Generated by Django 5.1.4 on 2025-02-09 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0015_customuser_user_profile_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='user_profile_updated',
        ),
        migrations.AddField(
            model_name='department',
            name='profile_updated',
            field=models.BooleanField(default=False),
        ),
    ]
