# Generated by Django 5.1.4 on 2025-02-09 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0016_remove_customuser_user_profile_updated_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='profile_updated',
        ),
        migrations.AddField(
            model_name='patient',
            name='profile_updated',
            field=models.BooleanField(default=False),
        ),
    ]
