# Generated by Django 5.1.4 on 2025-01-24 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0016_alter_doctor_license_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('Patient', 'Patient'), ('Doctor', 'Doctor'), ('Staff', 'Staff')], default='Patient', max_length=20),
        ),
    ]
