# Generated by Django 5.1.4 on 2025-01-24 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0017_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('Patient', 'Patient'), ('Administrator', 'Administrator'), ('Doctor', 'Doctor'), ('Staff', 'Staff')], default='Patient', max_length=20),
        ),
    ]
