# Generated by Django 5.1.4 on 2025-01-24 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0018_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='country',
            field=models.CharField(blank=True, default='', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('Patient', 'Patient'), ('Doctor', 'Doctor'), ('Staff', 'Staff')], default='Patient', max_length=20),
        ),
    ]
