# Generated by Django 5.1.4 on 2025-02-10 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0018_remove_schedule_end_date_remove_schedule_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
