# Generated by Django 5.1.6 on 2025-02-11 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0019_schedule_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'get_latest_by': ['created_at']},
        ),
    ]
