# Generated by Django 5.1.6 on 2025-02-11 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0020_alter_schedule_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='profile_updated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='staff',
            name='profile_updated',
            field=models.BooleanField(default=False),
        ),
    ]
