# Generated by Django 5.1.4 on 2025-01-24 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0020_schedules_alter_appointment_appointment_on_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Schedules',
            new_name='Schedule',
        ),
    ]
