# Generated by Django 5.1.6 on 2025-02-11 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0022_alter_department_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='slug',
        ),
    ]
