# Generated by Django 5.1.4 on 2025-01-24 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0022_schedule_end_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='end_date',
        ),
    ]
