# Generated by Django 5.1.4 on 2025-02-13 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0027_rename_record_date_medicalrecord_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='is_opened',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('SH', 'Scheduled'), ('RP', 'Reported'), ('CO', 'Completed'), ('CA', 'Cancelled'), ('NS', 'Noshow')], default='SH', max_length=2),
        ),
    ]
