# Generated by Django 5.1.4 on 2025-02-14 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0029_alter_medicalrecord_is_closed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecord',
            name='is_closed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
