# Generated by Django 5.1.4 on 2025-02-14 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0030_alter_medicalrecord_is_closed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='status',
            field=models.CharField(choices=[('PD', 'Paid'), ('PE', 'Pending'), ('UP', 'Unpaid')], default='PE', max_length=2),
        ),
    ]
