# Generated by Django 5.1.4 on 2025-02-14 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0031_alter_billing_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='password_request',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
