# Generated by Django 5.1.4 on 2025-02-15 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0032_doctor_password_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
