# Generated by Django 5.1.4 on 2025-02-15 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0033_alter_customuser_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalrecord',
            name='department',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='patient',
        ),
        migrations.AddField(
            model_name='appointment',
            name='follow_up',
            field=models.DateTimeField(null=True),
        ),
    ]
