# Generated by Django 5.1.4 on 2025-02-18 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0036_contactus_created_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Billing',
        ),
    ]
