# Generated by Django 5.1.4 on 2025-02-22 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0038_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
