# Generated by Django 5.1.4 on 2025-02-22 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0039_doctor_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='is_active',
        ),
    ]
