# Generated by Django 5.1.4 on 2025-02-22 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0040_remove_doctor_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='password_request',
        ),
        migrations.AddField(
            model_name='customuser',
            name='password_request',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
